from pathlib import Path


DATA_DIR = Path("data")

MARKET_DATA_PATH = DATA_DIR / "market_data.parquet"
HOLDINGS_PATH = DATA_DIR / "holdings.parquet"
TRADES_PATH = DATA_DIR / "trades.parquet"

JOURNAL_DAILY_PATH = DATA_DIR / "journal_daily.parquet"
JOURNAL_SUMMARY_PATH = DATA_DIR / "journal_summary.json"

INITIAL_CAPITAL = 1_000_000.0
TRADING_DAYS_PER_YEAR = 252

# Cost assumptions
SLIPPAGE_BPS = 10.0
COMMISSION_BPS = 0.0

# Optional benchmark behavior
USE_EQUAL_WEIGHT_UNIVERSE_BENCHMARK = True

# Volatility targeting parameters
ENABLE_VOLATILITY_TARGETING = True
TARGET_ANNUALIZED_VOLATILITY = 0.18
VOLATILITY_LOOKBACK_DAYS = 20
MIN_EXPOSURE = 0.25
MAX_EXPOSURE = 1.00

# Regime filter parameters
ENABLE_REGIME_FILTER = False
REGIME_LOOKBACK_DAYS = 20
REGIME_MIN_PERIODS = 20
REGIME_EXPOSURE_WHEN_NEGATIVE = 0.50
REGIME_EXPOSURE_WHEN_POSITIVE = 1.00